---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pivnet-opsman-product
  type: pivnet
  source:
    api_token: dx9snexN1CveTioPtrHU
    product_slug: ops-manager
    product_version: 2\.5\.8
- name: config
  type: git
  source:
    uri: http://www.github.com/ahartpence/config
    branch: master

jobs:
- name: upload-to-vcenter
  plan:
    - get: config
    - get: pivnet-opsman-product
      params:
        globs:
        - "*vsphere*"
    - task: upload
      file: config/task.yml
      params:
        GOVC_URL: vsphere.lab.starkandwayne.com
        GOVC_PASSWORD: q2rt8$$42U7PEz6W
        GOVC_USERNAME: ahartpence-lab
        GOVC_DATASTORE: iSCSI-1
        OPSMAN_IP: 10.128.192.205
        OM_GATEWAY: 10.128.0.1
        OM_DNS_SERVERS: 10.128.0.1
        OM_VM_FOLDER: snw-ahartpence-lab
        